### ISSUE TITLE
Feature request : new icons

### ISSUE THREAD

**Issue by egofree71** [enigma-dev/Calico-Icon#3]
I added the following icons : add-on-top.png, add-multiple.png, select-object.png, select-region.png and snap-to-grid.png.
The icons add-on-top.png and snap-to-grid.png need to be vectorized in order to make them less  aliased.
We need also a contrast icon pack for all new icons for the dark theme.

**Comment by JoshDreamland** [comment]
I believe the icons you're describing have been added as "AddLayer" and "MagnetGrid". What are the other two icons? I don't believe I've seen those before.
