### ISSUE TITLE
Export has incorrect alignment

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/Calico-Icon#4]
Just looking at the release after @rpjohnst pointed out to me that LGM had some misaligned icons. I thought at first it may have been my fault using Inkscape to export but it appears it's Calico's actual export script that must be doing it. You can see in the screenshot several of the icons are not centered properly.
![Left aligned](https://cloud.githubusercontent.com/assets/3212801/9725068/a05bba90-55ae-11e5-9f46-bbedc90ca91c.png)

**Comment by JoshDreamland** [comment]
Fixed in 6ff295665e661158e2f9b7a2d4d3397712047826.

**Comment by RobertBColton** [comment]
I can confirm that this does correct the issue, all of the icons I had to manually fix are now corrected. However, me you and @rpjohnst seem to have a different idea of how the left icon should be indented. I argue they should have the same left and right indent, and that is why @rpjohnst did yell at me for them being misaligned (even though you say they are).
